import { dataPath, executeOnLoad, fetchJsonAndThen, getSearchParamBool, just, } from "./utils.js";
import { createCopyButton, createWritingGallery, } from "./utils-portfolio.js";
let writingGallery;
let writingIntro;
let allowCopyingHtml = false;
let showHidden = false;
let projectJson;
function copyWritingHtml(writingGallery) {
    const text = (`
		<!-- 
		this is a static version of the writing gallery, 
		for folks who have javascript disabled. 
		automagically generated by The Power Of Five! <5 
		--> 
		${writingGallery.outerHTML}
		`
        .replace(/[\t\r\n]+/g, "")
        .replace('id="writing-gallery"', 'id="writing-gallery-s"'));
    navigator.clipboard.writeText(text);
}
function initialize() {
    if (allowCopyingHtml) {
        createCopyButton(writingIntro, () => { copyWritingHtml(writingGallery); });
    }
    createWritingGallery(writingGallery, { projectJson, showHidden });
}
function main() {
    writingGallery = just(document.getElementById("writing-gallery"));
    writingIntro = just(document.getElementById("writing-intro"));
    allowCopyingHtml = getSearchParamBool("copy");
    showHidden = getSearchParamBool("hidden");
    fetchJsonAndThen(`${dataPath}projects.json`, json => {
        projectJson = json;
        initialize();
    });
}
executeOnLoad(main);
